method: 'time_nonlocal' # Possible method: beta, uniform_norm, classical_CNN, gaussian, time_nonlocal
dataset: 'Iris' # Possible dataset: Iris, MNIST, MedMNIST
epochs: 100
barren_threshold: 1e-5
learning_rate: 0.01 # Possible Learning_rate: 0.0001 to 0.1
